export const restaurantsRoutes = (app) => {
  app.get('/restaurants', async (req, res) => {
    // const databaseRows = await getDatabaseRows(process.env.NOTION_TOKEN, process.env.NOTION_DATABASE_ID);
    return res.json([{
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{'id': '9ff470d5-844c-4b3f-a218-de3b27087d0a', 'name': 'J\'ai le temps 😎', 'color': 'green'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'ef633d5e-6e44-4a5c-82ec-1e51968c3f1d', 'name': '€€€', 'color': 'red'},
      },
      'À combien': {'id': 'F%3Ads', 'type': 'multi_select', 'multi_select': []},
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': 'fb866207-9924-4f75-9a56-37d3a3804fb3', 'name': 'Bof', 'color': 'orange'},
      },
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': 'Après 12h15', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Après 12h15',
          'href': null,
        }],
      },
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': null},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': '592137bd-c705-4c92-8976-8aefed952ac4', 'name': 'Dépend de toi', 'color': 'yellow'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '11 Rue de Montenotte, 75017 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '11 Rue de Montenotte, 75017 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'Pad thaï', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Pad thaï',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{
          'id': '29c9a208-6141-42f5-8d16-d811e42a6569',
          'name': 'Je suis pressé ⏲️',
          'color': 'red',
        }, {'id': '9ff470d5-844c-4b3f-a218-de3b27087d0a', 'name': 'J\'ai le temps 😎', 'color': 'green'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'e3e6d0b9-0d9a-443a-b4f0-52f37c2bd529', 'name': '€', 'color': 'green'},
      },
      'À combien': {
        'id': 'F%3Ads',
        'type': 'multi_select',
        'multi_select': [{
          'id': '1781db83-c321-46e9-b9d1-bee4acbfbbe2',
          'name': 'Groupe moyen (4-6)',
          'color': 'yellow',
        }],
      },
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': '575b26a8-5d2f-44e5-993f-429be8a1ca50', 'name': 'Oui', 'color': 'green'},
      },
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': 'n’importe', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'n’importe',
          'href': null,
        }],
      },
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': 'www.nagoyaparis17.fr'},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': '592137bd-c705-4c92-8976-8aefed952ac4', 'name': 'Dépend de toi', 'color': 'yellow'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '16 rue Brey 75017 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '16 rue Brey 75017 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'Nagoya (restaurant japonais)', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Nagoya (restaurant japonais)',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{'id': '29c9a208-6141-42f5-8d16-d811e42a6569', 'name': 'Je suis pressé ⏲️', 'color': 'red'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'e3e6d0b9-0d9a-443a-b4f0-52f37c2bd529', 'name': '€', 'color': 'green'},
      },
      'À combien': {
        'id': 'F%3Ads',
        'type': 'multi_select',
        'multi_select': [{
          'id': '1781db83-c321-46e9-b9d1-bee4acbfbbe2',
          'name': 'Groupe moyen (4-6)',
          'color': 'yellow',
        }],
      },
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': '575b26a8-5d2f-44e5-993f-429be8a1ca50', 'name': 'Oui', 'color': 'green'},
      },
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': 'n\'importe', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'n\'importe',
          'href': null,
        }],
      },
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': null},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': '592137bd-c705-4c92-8976-8aefed952ac4', 'name': 'Dépend de toi', 'color': 'yellow'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '47 Rue des Acacias, 75017 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '47 Rue des Acacias, 75017 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'Subway', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Subway',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{
          'id': '29c9a208-6141-42f5-8d16-d811e42a6569',
          'name': 'Je suis pressé ⏲️',
          'color': 'red',
        }, {
          'id': 'bc92109a-d6e8-4796-8d91-93403d2ac0eb',
          'name': 'Pas quand il pleut ( trop loin ) ☔',
          'color': 'blue',
        }],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'e3e6d0b9-0d9a-443a-b4f0-52f37c2bd529', 'name': '€', 'color': 'green'},
      },
      'À combien': {
        'id': 'F%3Ads',
        'type': 'multi_select',
        'multi_select': [{
          'id': '1781db83-c321-46e9-b9d1-bee4acbfbbe2',
          'name': 'Groupe moyen (4-6)',
          'color': 'yellow',
        }],
      },
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': '575b26a8-5d2f-44e5-993f-429be8a1ca50', 'name': 'Oui', 'color': 'green'},
      },
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '12h00', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '12h00',
          'href': null,
        }],
      },
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': 'https://www.bagelstein.com/carte/nos-bagels'},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': 'bdc1a7e2-afcb-4bf7-8b24-e77168006940', 'name': 'Healthy', 'color': 'purple'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '8 Av. Carnot, 75017 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '8 Av. Carnot, 75017 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'Bagelsteins', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Bagelsteins',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{
          'id': 'bc92109a-d6e8-4796-8d91-93403d2ac0eb',
          'name': 'Pas quand il pleut ( trop loin ) ☔',
          'color': 'blue',
        }],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'dbdb065d-2e0b-4a31-8aa2-75afb3f415ae', 'name': '€€', 'color': 'orange'},
      },
      'À combien': {'id': 'F%3Ads', 'type': 'multi_select', 'multi_select': []},
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': '575b26a8-5d2f-44e5-993f-429be8a1ca50', 'name': 'Oui', 'color': 'green'},
      },
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': 'N\'importe pas mal de choix', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'N\'importe pas mal de choix',
          'href': null,
        }],
      },
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': 'http://boulangerie-montgolfiere.fr/'},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': 'bdc1a7e2-afcb-4bf7-8b24-e77168006940', 'name': 'Healthy', 'color': 'purple'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '49 rue Laugier', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '49 rue Laugier',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'Boulangerie La Montgolfiere', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Boulangerie La Montgolfiere',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{'id': '9ff470d5-844c-4b3f-a218-de3b27087d0a', 'name': 'J\'ai le temps 😎', 'color': 'green'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'ef633d5e-6e44-4a5c-82ec-1e51968c3f1d', 'name': '€€€', 'color': 'red'},
      },
      'À combien': {'id': 'F%3Ads', 'type': 'multi_select', 'multi_select': []},
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': '9e568b15-fa8e-421b-88dd-c72df191613b', 'name': 'Non', 'color': 'red'},
      },
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': 'reserver', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'reserver',
          'href': null,
        }],
      },
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': 'http://www.crabemarteau.fr/'},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': '592137bd-c705-4c92-8976-8aefed952ac4', 'name': 'Dépend de toi', 'color': 'yellow'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '16 rue des Acacias ', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '16 rue des Acacias ',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'Crabe Marteau', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Crabe Marteau',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{'id': '29c9a208-6141-42f5-8d16-d811e42a6569', 'name': 'Je suis pressé ⏲️', 'color': 'red'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'e3e6d0b9-0d9a-443a-b4f0-52f37c2bd529', 'name': '€', 'color': 'green'},
      },
      'À combien': {
        'id': 'F%3Ads',
        'type': 'multi_select',
        'multi_select': [{
          'id': 'e09d9f03-cd99-439f-878e-c5c3c601a95b',
          'name': 'Petit commité (1-3)',
          'color': 'green',
        }],
      },
      'Option végé': {'id': 'FKBn', 'type': 'select', 'select': null},
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': 'n\'importe', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'n\'importe',
          'href': null,
        }],
      },
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': 'http://www.latelierlibanais.fr/'},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': 'bdc1a7e2-afcb-4bf7-8b24-e77168006940', 'name': 'Healthy', 'color': 'purple'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '270 Rue du Faubourg Saint-Honoré, 75008 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '270 Rue du Faubourg Saint-Honoré, 75008 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'L\'atelier libanais/traiteur', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'L\'atelier libanais/traiteur',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{
          'id': 'bc92109a-d6e8-4796-8d91-93403d2ac0eb',
          'name': 'Pas quand il pleut ( trop loin ) ☔',
          'color': 'blue',
        }, {'id': '29c9a208-6141-42f5-8d16-d811e42a6569', 'name': 'Je suis pressé ⏲️', 'color': 'red'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'dbdb065d-2e0b-4a31-8aa2-75afb3f415ae', 'name': '€€', 'color': 'orange'},
      },
      'À combien': {'id': 'F%3Ads', 'type': 'multi_select', 'multi_select': []},
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': '575b26a8-5d2f-44e5-993f-429be8a1ca50', 'name': 'Oui', 'color': 'green'},
      },
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': 'N\'importe, et peut livrer ', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'N\'importe, et peut livrer ',
          'href': null,
        }],
      },
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': 'https://www.clasico-argentino.com/'},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': '592137bd-c705-4c92-8976-8aefed952ac4', 'name': 'Dépend de toi', 'color': 'yellow'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '25 Rue Pierre Demours, 75017 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '25 Rue Pierre Demours, 75017 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'Clasico Argentino Ternes (Empanadas)', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Clasico Argentino Ternes (Empanadas)',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{'id': '9ff470d5-844c-4b3f-a218-de3b27087d0a', 'name': 'J\'ai le temps 😎', 'color': 'green'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'ef633d5e-6e44-4a5c-82ec-1e51968c3f1d', 'name': '€€€', 'color': 'red'},
      },
      'À combien': {'id': 'F%3Ads', 'type': 'multi_select', 'multi_select': []},
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': '575b26a8-5d2f-44e5-993f-429be8a1ca50', 'name': 'Oui', 'color': 'green'},
      },
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '12h', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '12h',
          'href': null,
        }],
      },
      'Menu': {
        'id': 'j%60Tz',
        'type': 'url',
        'url': 'https://www.google.com/maps/uv?pb=!1s0x47e66feb6bc9648d%3A0xb9e9b657d8729bc9!3m1!7e115!4shttps%3A%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipNlqDLbqA37cywdn6dYTfjDVelzFLcRabbxY8om%3Dw213-h160-k-no!5szenzan%20-%20Recherche%20Google!15sCgIYIQ&imagekey=!1e10!2sAF1QipOzFUS-BA3BhsT98MjYlqKqxdLh0imUU1Eg6Zu7&hl=fr&sa=X&ved=2ahUKEwiSg7n108_0AhWIxYUKHfEfDL4Qoip6BAhSEAM',
      },
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': '592137bd-c705-4c92-8976-8aefed952ac4', 'name': 'Dépend de toi', 'color': 'yellow'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': 'Rue Brey, 75017 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Rue Brey, 75017 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'Zenzan', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Zenzan',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{'id': '9ff470d5-844c-4b3f-a218-de3b27087d0a', 'name': 'J\'ai le temps 😎', 'color': 'green'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'dbdb065d-2e0b-4a31-8aa2-75afb3f415ae', 'name': '€€', 'color': 'orange'},
      },
      'À combien': {
        'id': 'F%3Ads',
        'type': 'multi_select',
        'multi_select': [{
          'id': 'e09d9f03-cd99-439f-878e-c5c3c601a95b',
          'name': 'Petit commité (1-3)',
          'color': 'green',
        }],
      },
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': '575b26a8-5d2f-44e5-993f-429be8a1ca50', 'name': 'Oui', 'color': 'green'},
      },
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '12H00, après c\'est blindé', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '12H00, après c\'est blindé',
          'href': null,
        }],
      },
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': null},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': '592137bd-c705-4c92-8976-8aefed952ac4', 'name': 'Dépend de toi', 'color': 'yellow'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '42 Rue des Acacias, 75017 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '42 Rue des Acacias, 75017 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'Siam Square (pad thaï)', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Siam Square (pad thaï)',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{'id': '29c9a208-6141-42f5-8d16-d811e42a6569', 'name': 'Je suis pressé ⏲️', 'color': 'red'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'e3e6d0b9-0d9a-443a-b4f0-52f37c2bd529', 'name': '€', 'color': 'green'},
      },
      'À combien': {'id': 'F%3Ads', 'type': 'multi_select', 'multi_select': []},
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': '575b26a8-5d2f-44e5-993f-429be8a1ca50', 'name': 'Oui', 'color': 'green'},
      },
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': 'N\'importe', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'N\'importe',
          'href': null,
        }],
      },
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': 'https://apertivus.net/'},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': '592137bd-c705-4c92-8976-8aefed952ac4', 'name': 'Dépend de toi', 'color': 'yellow'}],
      },
      'Adresse': {'id': 'sGSP', 'type': 'rich_text', 'rich_text': []},
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'Apertivus', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Apertivus',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{'id': '9ff470d5-844c-4b3f-a218-de3b27087d0a', 'name': 'J\'ai le temps 😎', 'color': 'green'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'dbdb065d-2e0b-4a31-8aa2-75afb3f415ae', 'name': '€€', 'color': 'orange'},
      },
      'À combien': {'id': 'F%3Ads', 'type': 'multi_select', 'multi_select': []},
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': '575b26a8-5d2f-44e5-993f-429be8a1ca50', 'name': 'Oui', 'color': 'green'},
      },
      'Meilleur horaire pour ne pas attendre': {'id': 'YR~z', 'type': 'rich_text', 'rich_text': []},
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': null},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': '592137bd-c705-4c92-8976-8aefed952ac4', 'name': 'Dépend de toi', 'color': 'yellow'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '9 Rue Poncelet, 75017 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '9 Rue Poncelet, 75017 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'Delitaly', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Delitaly',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{'id': '9ff470d5-844c-4b3f-a218-de3b27087d0a', 'name': 'J\'ai le temps 😎', 'color': 'green'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'e3e6d0b9-0d9a-443a-b4f0-52f37c2bd529', 'name': '€', 'color': 'green'},
      },
      'À combien': {'id': 'F%3Ads', 'type': 'multi_select', 'multi_select': []},
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': '575b26a8-5d2f-44e5-993f-429be8a1ca50', 'name': 'Oui', 'color': 'green'},
      },
      'Meilleur horaire pour ne pas attendre': {'id': 'YR~z', 'type': 'rich_text', 'rich_text': []},
      'Menu': {
        'id': 'j%60Tz',
        'type': 'url',
        'url': 'https://www.laouz.com/wp-content/uploads/2021/02/Carte-restauration-rapide.pdf',
      },
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': '592137bd-c705-4c92-8976-8aefed952ac4', 'name': 'Dépend de toi', 'color': 'yellow'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '23 Rue Poncelet, 75017 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '23 Rue Poncelet, 75017 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'Laouz', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Laouz',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{
          'id': 'bc92109a-d6e8-4796-8d91-93403d2ac0eb',
          'name': 'Pas quand il pleut ( trop loin ) ☔',
          'color': 'blue',
        }, {'id': '9ff470d5-844c-4b3f-a218-de3b27087d0a', 'name': 'J\'ai le temps 😎', 'color': 'green'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'dbdb065d-2e0b-4a31-8aa2-75afb3f415ae', 'name': '€€', 'color': 'orange'},
      },
      'À combien': {'id': 'F%3Ads', 'type': 'multi_select', 'multi_select': []},
      'Option végé': {'id': 'FKBn', 'type': 'select', 'select': null},
      'Meilleur horaire pour ne pas attendre': {'id': 'YR~z', 'type': 'rich_text', 'rich_text': []},
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': 'https://www.gbygaspard.fr/menu'},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': '592137bd-c705-4c92-8976-8aefed952ac4', 'name': 'Dépend de toi', 'color': 'yellow'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '10 Rue Villebois-Mareuil, 75017 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '10 Rue Villebois-Mareuil, 75017 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'G by Gaspard Ternes (naans) ', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'G by Gaspard Ternes (naans) ',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{'id': '9ff470d5-844c-4b3f-a218-de3b27087d0a', 'name': 'J\'ai le temps 😎', 'color': 'green'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'dbdb065d-2e0b-4a31-8aa2-75afb3f415ae', 'name': '€€', 'color': 'orange'},
      },
      'À combien': {'id': 'F%3Ads', 'type': 'multi_select', 'multi_select': []},
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': '575b26a8-5d2f-44e5-993f-429be8a1ca50', 'name': 'Oui', 'color': 'green'},
      },
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': 'Pas d\'infos', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Pas d\'infos',
          'href': null,
        }],
      },
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': 'https://www.delpapa.fr/menus'},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': '592137bd-c705-4c92-8976-8aefed952ac4', 'name': 'Dépend de toi', 'color': 'yellow'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '233Bis Rue du Faubourg Saint-Honoré, 75008 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '233Bis Rue du Faubourg Saint-Honoré, 75008 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'Del Papa', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Del Papa',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{'id': '29c9a208-6141-42f5-8d16-d811e42a6569', 'name': 'Je suis pressé ⏲️', 'color': 'red'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'e3e6d0b9-0d9a-443a-b4f0-52f37c2bd529', 'name': '€', 'color': 'green'},
      },
      'À combien': {
        'id': 'F%3Ads',
        'type': 'multi_select',
        'multi_select': [{
          'id': '1781db83-c321-46e9-b9d1-bee4acbfbbe2',
          'name': 'Groupe moyen (4-6)',
          'color': 'yellow',
        }],
      },
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': '9e568b15-fa8e-421b-88dd-c72df191613b', 'name': 'Non', 'color': 'red'},
      },
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': 'N\'importe', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'N\'importe',
          'href': null,
        }],
      },
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': null},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': '3cc4bea1-0527-4cbb-92ae-0ba9b48b5622', 'name': 'Saaaale', 'color': 'green'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '15 Av. de Wagram, 75017 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '15 Av. de Wagram, 75017 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'O\'Tacos', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'O\'Tacos',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {'id': '%3EE%7CM', 'type': 'multi_select', 'multi_select': []},
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'dbdb065d-2e0b-4a31-8aa2-75afb3f415ae', 'name': '€€', 'color': 'orange'},
      },
      'À combien': {
        'id': 'F%3Ads',
        'type': 'multi_select',
        'multi_select': [{
          'id': 'e09d9f03-cd99-439f-878e-c5c3c601a95b',
          'name': 'Petit commité (1-3)',
          'color': 'green',
        }],
      },
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': '575b26a8-5d2f-44e5-993f-429be8a1ca50', 'name': 'Oui', 'color': 'green'},
      },
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': 'Pas après 12h30', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Pas après 12h30',
          'href': null,
        }],
      },
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': 'https://www.bobosnack.com/'},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': '592137bd-c705-4c92-8976-8aefed952ac4', 'name': 'Dépend de toi', 'color': 'yellow'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '12 bis rue de l\'etoile, Paris, 75017', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '12 bis rue de l\'etoile, Paris, 75017',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'Bobo Snack', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Bobo Snack',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {'id': '%3EE%7CM', 'type': 'multi_select', 'multi_select': []},
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'dbdb065d-2e0b-4a31-8aa2-75afb3f415ae', 'name': '€€', 'color': 'orange'},
      },
      'À combien': {
        'id': 'F%3Ads',
        'type': 'multi_select',
        'multi_select': [{
          'id': '1781db83-c321-46e9-b9d1-bee4acbfbbe2',
          'name': 'Groupe moyen (4-6)',
          'color': 'yellow',
        }],
      },
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': '575b26a8-5d2f-44e5-993f-429be8a1ca50', 'name': 'Oui', 'color': 'green'},
      },
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': 'possible de réserver avant 11h', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'possible de réserver avant 11h',
          'href': null,
        }],
      },
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': 'https://cclique.fr/paris/popotes-cantine-respectueuse-macmahon'},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': 'bdc1a7e2-afcb-4bf7-8b24-e77168006940', 'name': 'Healthy', 'color': 'purple'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '18 Av. Mac-Mahon, 75017 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '18 Av. Mac-Mahon, 75017 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'Popotes', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Popotes',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{'id': '9ff470d5-844c-4b3f-a218-de3b27087d0a', 'name': 'J\'ai le temps 😎', 'color': 'green'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'ef633d5e-6e44-4a5c-82ec-1e51968c3f1d', 'name': '€€€', 'color': 'red'},
      },
      'À combien': {'id': 'F%3Ads', 'type': 'multi_select', 'multi_select': []},
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': 'fb866207-9924-4f75-9a56-37d3a3804fb3', 'name': 'Bof', 'color': 'orange'},
      },
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '12H00, après c\'est blindé', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '12H00, après c\'est blindé',
          'href': null,
        }],
      },
      'Menu': {
        'id': 'j%60Tz',
        'type': 'url',
        'url': 'https://www.eat-list.fr/paris-8-75008/sushi-et-japonais-1/okame-3437',
      },
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': 'bdc1a7e2-afcb-4bf7-8b24-e77168006940', 'name': 'Healthy', 'color': 'purple'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '235 Rue du Faubourg Saint-Honoré, 75008 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '235 Rue du Faubourg Saint-Honoré, 75008 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'Okame', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Okame',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{'id': '29c9a208-6141-42f5-8d16-d811e42a6569', 'name': 'Je suis pressé ⏲️', 'color': 'red'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'e3e6d0b9-0d9a-443a-b4f0-52f37c2bd529', 'name': '€', 'color': 'green'},
      },
      'À combien': {
        'id': 'F%3Ads',
        'type': 'multi_select',
        'multi_select': [{
          'id': '1781db83-c321-46e9-b9d1-bee4acbfbbe2',
          'name': 'Groupe moyen (4-6)',
          'color': 'yellow',
        }],
      },
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': '575b26a8-5d2f-44e5-993f-429be8a1ca50', 'name': 'Oui', 'color': 'green'},
      },
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': 'N\'importe', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'N\'importe',
          'href': null,
        }],
      },
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': null},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': '592137bd-c705-4c92-8976-8aefed952ac4', 'name': 'Dépend de toi', 'color': 'yellow'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '10 Rue Bayen, 75017 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '10 Rue Bayen, 75017 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'Shine Garden', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Shine Garden',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{'id': '29c9a208-6141-42f5-8d16-d811e42a6569', 'name': 'Je suis pressé ⏲️', 'color': 'red'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'e3e6d0b9-0d9a-443a-b4f0-52f37c2bd529', 'name': '€', 'color': 'green'},
      },
      'À combien': {
        'id': 'F%3Ads',
        'type': 'multi_select',
        'multi_select': [{
          'id': 'd2dbde30-44a1-4920-825b-4f37ba34ef2b',
          'name': 'Grosse équipe (7-infini)',
          'color': 'red',
        }],
      },
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': '575b26a8-5d2f-44e5-993f-429be8a1ca50', 'name': 'Oui', 'color': 'green'},
      },
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '12H00', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '12H00',
          'href': null,
        }],
      },
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': null},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': '3cc4bea1-0527-4cbb-92ae-0ba9b48b5622', 'name': 'Saaaale', 'color': 'green'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '7 Av. de Wagram, 75017 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '7 Av. de Wagram, 75017 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'Burger King', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Burger King',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{
          'id': 'bc92109a-d6e8-4796-8d91-93403d2ac0eb',
          'name': 'Pas quand il pleut ( trop loin ) ☔',
          'color': 'blue',
        }, {'id': '9ff470d5-844c-4b3f-a218-de3b27087d0a', 'name': 'J\'ai le temps 😎', 'color': 'green'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'e3e6d0b9-0d9a-443a-b4f0-52f37c2bd529', 'name': '€', 'color': 'green'},
      },
      'À combien': {
        'id': 'F%3Ads',
        'type': 'multi_select',
        'multi_select': [{
          'id': 'e09d9f03-cd99-439f-878e-c5c3c601a95b',
          'name': 'Petit commité (1-3)',
          'color': 'green',
        }],
      },
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': '575b26a8-5d2f-44e5-993f-429be8a1ca50', 'name': 'Oui', 'color': 'green'},
      },
      'Meilleur horaire pour ne pas attendre': {'id': 'YR~z', 'type': 'rich_text', 'rich_text': []},
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': null},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': '3cc4bea1-0527-4cbb-92ae-0ba9b48b5622', 'name': 'Saaaale', 'color': 'green'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '30 Rue des Acacias, 75017 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '30 Rue des Acacias, 75017 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'I ♥️ Burger', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'I ♥️ Burger',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{'id': '29c9a208-6141-42f5-8d16-d811e42a6569', 'name': 'Je suis pressé ⏲️', 'color': 'red'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'e3e6d0b9-0d9a-443a-b4f0-52f37c2bd529', 'name': '€', 'color': 'green'},
      },
      'À combien': {
        'id': 'F%3Ads',
        'type': 'multi_select',
        'multi_select': [{
          'id': 'd2dbde30-44a1-4920-825b-4f37ba34ef2b',
          'name': 'Grosse équipe (7-infini)',
          'color': 'red',
        }],
      },
      'Option végé': {
        'id': 'FKBn',
        'type': 'select',
        'select': {'id': '575b26a8-5d2f-44e5-993f-429be8a1ca50', 'name': 'Oui', 'color': 'green'},
      },
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': 'N\'importe', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'N\'importe',
          'href': null,
        }],
      },
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': null},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': '3cc4bea1-0527-4cbb-92ae-0ba9b48b5622', 'name': 'Saaaale', 'color': 'green'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '11 Av. de Wagram, 75017 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '11 Av. de Wagram, 75017 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'McDonald\'s', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'McDonald\'s',
          'href': null,
        }],
      },
    }, {
      'Contrainte': {
        'id': '%3EE%7CM',
        'type': 'multi_select',
        'multi_select': [{'id': '9ff470d5-844c-4b3f-a218-de3b27087d0a', 'name': 'J\'ai le temps 😎', 'color': 'green'}],
      },
      'Prix': {
        'id': '%40Vx%7C',
        'type': 'select',
        'select': {'id': 'dbdb065d-2e0b-4a31-8aa2-75afb3f415ae', 'name': '€€', 'color': 'orange'},
      },
      'À combien': {'id': 'F%3Ads', 'type': 'multi_select', 'multi_select': []},
      'Option végé': {'id': 'FKBn', 'type': 'select', 'select': null},
      'Meilleur horaire pour ne pas attendre': {
        'id': 'YR~z',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': 'N\'importe', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'N\'importe',
          'href': null,
        }],
      },
      'Menu': {'id': 'j%60Tz', 'type': 'url', 'url': 'http://www.restaurant-kyofuji.com/'},
      'Mood': {
        'id': 'rAjm',
        'type': 'multi_select',
        'multi_select': [{'id': 'bdc1a7e2-afcb-4bf7-8b24-e77168006940', 'name': 'Healthy', 'color': 'purple'}],
      },
      'Adresse': {
        'id': 'sGSP',
        'type': 'rich_text',
        'rich_text': [{
          'type': 'text',
          'text': {'content': '17 Rue de l\'étoile, 75017 Paris', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': '17 Rue de l\'étoile, 75017 Paris',
          'href': null,
        }],
      },
      'Name': {
        'id': 'title',
        'type': 'title',
        'title': [{
          'type': 'text',
          'text': {'content': 'Kyo Sushi', 'link': null},
          'annotations': {
            'bold': false,
            'italic': false,
            'strikethrough': false,
            'underline': false,
            'code': false,
            'color': 'default',
          },
          'plain_text': 'Kyo Sushi',
          'href': null,
        }],
      },
    }]);
  });
}
